name: Android APK Auto-Compiler

on:
  push:
    branches: [ "main", "master" ]

jobs:
  compiler-job:
    runs-on: ubuntu-latest

    steps:
    - name: Download Source Code
      uses: actions/checkout@v4

    - name: Initialize JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Fix Windows Line Endings and Grant Execute Rights
      run: |
        sed -i 's/\r$//' gradlew
        chmod +x gradlew

    # Мы добавили "clean", чтобы полностью стереть старый кэш ресурсов
    - name: Compile Application (Assemble Debug APK)
      run: ./gradlew clean assembleDebug

    - name: Save APK to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: minimal-excel-editor
        path: app/build/outputs/apk/debug/app-debug.apk
